# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-17 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodPlayaApp', '0002_customer_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='name',
            new_name='avatar',
        ),
    ]
