# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodPlayaApp', '0006_orderdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='OrderDetails',
        ),
    ]
