# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-23 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodPlayaApp', '0007_auto_20180220_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodPlayaApp.Driver'),
        ),
    ]
